service: python-sqlite-layers
#frameworkVersion: ">=1.34.0 <2.0.0"

provider:
  name: aws

layers:
  sqlitePython36:
    path: layer
    description: A Layer to fix SQLite support in Python 3.6 Lambda functions
    compatibleRuntimes:
      - python3.6
